#!/usr/bin/env perl

use strict;

my $readme_pod = do {
	open my $fh, 'README.pod' or die $!;
	local $/;
	<$fh>;
};

my $docs_pod;
open my $fh, 'bootylicious' or die $!;

while (my $line = <$fh>) {
	last if $line =~ /^__END__/;
}
while (my $line = <$fh>) {
	$docs_pod .= $line;
}

if ($readme_pod ne $docs_pod) {
	open $fh, '>', 'README.pod' or die $!;
	print $fh $docs_pod;
	close $fh;
	die "README.pod updated, repeat your commit command\n";
}
